#!/bin/sh

TAG=$(git rev-parse --short HEAD)
TI=""
[ -t 0 ] && TI="-ti"

docker image inspect metroaeconfig:$TAG > /dev/null 2>&1
if [[ "$?" != "0" ]]
then
    if [[ -n "$TI" ]]
    then
        echo "The docker image for this repo head does not exist. We will build it. Press any key to continue"
        read -n 1
    fi
    set -e
    ./docker/build-container raw
    set +e
fi

# Run the command inside docker
args=( "$@" )

docker run --rm $TI -v "`pwd`:/metroaeconfig" metroaeconfig:$TAG python3 metroae_config.py "${args[@]}"

