name: IngressQosPolicy
description: QoS template set - Create an Ingress QoS Policy
template-version: 1.0
software-type: Nuage Networks VSD
software-version: 5.1.1
variables:
  - name: enterprise_name
    type: reference
    optional: true
  - name: description
    type: string
    optional: true
  - name: ingress_qos_policy_name
    type: reference
  - name: parent_rate_limiter_name
    type: reference
  - name: priority_queue_1_classes
    type: list
    item-type: choice
    choices: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
    optional: true
  - name: priority_queue_1_rate_limiter_name
    type: reference
    optional: true
  - name: wrr_queue_2_classes
    type: list
    item-type: choice
    choices: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
    optional: true
  - name: wrr_queue_2_rate_limiter_name
    type: reference
    optional: true
  - name: wrr_queue_3_classes
    type: list
    item-type: choice
    choices: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
    optional: true
  - name: wrr_queue_3_rate_limiter_name
    type: reference
    optional: true
  - name: wrr_queue_4_classes
    type: list
    item-type: choice
    choices: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
    optional: true
  - name: wrr_queue_4_rate_limiter_name
    type: reference
    optional: true
actions:
  {% if enterprise_name is defined %}
  - select-object:
      type: Enterprise
      by-field: name
      value: {{ enterprise_name }}
      actions:
  {% endif %}
        - select-object:
            type: RateLimiter
            by-field: name
            value: {{ parent_rate_limiter_name }}
            actions:
              - store-value:
                  as-name: parent_rate_limiter_id
                  from-field: id
        {% if priority_queue_1_rate_limiter_name is defined %}
        - select-object:
            type: RateLimiter
            by-field: name
            value: {{ priority_queue_1_rate_limiter_name }}
            actions:
              - store-value:
                  as-name: priority_queue_1_rate_limiter_id
                  from-field: id
        {% endif %}
        {% if wrr_queue_2_rate_limiter_name is defined %}
        - select-object:
            type: RateLimiter
            by-field: name
            value: {{ wrr_queue_2_rate_limiter_name }}
            actions:
              - store-value:
                  as-name: wrr_queue_2_rate_limiter_id
                  from-field: id
        {% endif %}
        {% if wrr_queue_3_rate_limiter_name is defined %}
        - select-object:
            type: RateLimiter
            by-field: name
            value: {{ wrr_queue_3_rate_limiter_name }}
            actions:
              - store-value:
                  as-name: wrr_queue_3_rate_limiter_id
                  from-field: id
        {% endif %}
        {% if wrr_queue_4_rate_limiter_name is defined %}
        - select-object:
            type: RateLimiter
            by-field: name
            value: {{ wrr_queue_4_rate_limiter_name }}
            actions:
              - store-value:
                  as-name: wrr_queue_4_rate_limiter_id
                  from-field: id
        {% endif %}
        - create-object:
            type: IngressQOSPolicy
            actions:
              - set-values:
                  name: {{ ingress_qos_policy_name }}
                  description: {{ description | default("ingress QoS policy " + ingress_qos_policy_name | default("")) }}
                  queue1ForwardingClasses: {{ priority_queue_1_classes | default(None) }}
                  queue2ForwardingClasses: {{ wrr_queue_2_classes | default(None) }}
                  queue3ForwardingClasses: {{ wrr_queue_3_classes | default(None) }}
                  queue4ForwardingClasses: {{ wrr_queue_4_classes | default(None) }}
              - retrieve-value:
                  from-name: parent_rate_limiter_id
                  to-field: parentQueueAssociatedRateLimiterID
              {% if priority_queue_1_rate_limiter_name is defined %}
              - retrieve-value:
                  from-name: priority_queue_1_rate_limiter_id
                  to-field: queue1AssociatedRateLimiterID
              {% endif %}
              {% if wrr_queue_2_rate_limiter_name is defined %}
              - retrieve-value:
                  from-name: wrr_queue_2_rate_limiter_id
                  to-field: queue2AssociatedRateLimiterID
              {% endif %}
              {% if wrr_queue_3_rate_limiter_name is defined %}
              - retrieve-value:
                  from-name: wrr_queue_3_rate_limiter_id
                  to-field: queue3AssociatedRateLimiterID
              {% endif %}
              {% if wrr_queue_4_rate_limiter_name is defined %}
              - retrieve-value:
                  from-name: wrr_queue_4_rate_limiter_id
                  to-field: queue4AssociatedRateLimiterID
              {% endif %}
